// <auto-generated />
using System;
using InstrumentCatalogue.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace InstrumentCatalogue.Infrastructure.Migrations
{
    [DbContext(typeof(CatalogueDbContext))]
    [Migration("20260613184816_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.27")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("InstrumentCatalogue.Core.Models.BondRefData", b =>
                {
                    b.Property<Guid>("InstrumentId")
                        .HasColumnType("uuid")
                        .HasColumnName("instrument_id");

                    b.Property<string>("BondStructure")
                        .HasColumnType("text")
                        .HasColumnName("bond_structure");

                    b.Property<string>("BondType")
                        .HasColumnType("text")
                        .HasColumnName("bond_type");

                    b.Property<string>("CouponFrequency")
                        .HasColumnType("text")
                        .HasColumnName("coupon_frequency");

                    b.Property<decimal?>("CouponRate")
                        .HasPrecision(8, 6)
                        .HasColumnType("numeric(8,6)")
                        .HasColumnName("coupon_rate");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("CreditRating")
                        .HasMaxLength(25)
                        .HasColumnType("character varying(25)")
                        .HasColumnName("credit_rating");

                    b.Property<decimal?>("Duration")
                        .HasPrecision(8, 6)
                        .HasColumnType("numeric(8,6)")
                        .HasColumnName("duration");

                    b.Property<decimal>("FaceValue")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)")
                        .HasColumnName("face_value");

                    b.Property<DateOnly?>("IssueDate")
                        .HasColumnType("date")
                        .HasColumnName("issue_date");

                    b.Property<string>("Issuer")
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("issuer");

                    b.Property<DateTime>("LastUpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_updated_at_utc");

                    b.Property<DateOnly?>("MaturityDate")
                        .HasColumnType("date")
                        .HasColumnName("maturity_date");

                    b.HasKey("InstrumentId")
                        .HasName("pk_bond_ref_data");

                    b.ToTable("bond_ref_data", (string)null);
                });

            modelBuilder.Entity("InstrumentCatalogue.Core.Models.EquityRefData", b =>
                {
                    b.Property<Guid>("InstrumentId")
                        .HasColumnType("uuid")
                        .HasColumnName("instrument_id");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("Industry")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("industry");

                    b.Property<DateTime>("LastUpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_updated_at_utc");

                    b.Property<int>("LotSize")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(1)
                        .HasColumnName("lot_size");

                    b.Property<decimal?>("ParValue")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)")
                        .HasColumnName("par_value");

                    b.Property<string>("Sector")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("sector");

                    b.Property<long?>("SharesOutstanding")
                        .HasColumnType("bigint")
                        .HasColumnName("shares_outstanding");

                    b.HasKey("InstrumentId")
                        .HasName("pk_equity_ref_data");

                    b.ToTable("equity_ref_data", (string)null);
                });

            modelBuilder.Entity("InstrumentCatalogue.Core.Models.EtfRefData", b =>
                {
                    b.Property<Guid>("InstrumentId")
                        .HasColumnType("uuid")
                        .HasColumnName("instrument_id");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("DistributionFrequency")
                        .HasColumnType("text")
                        .HasColumnName("distribution_frequency");

                    b.Property<decimal?>("ExpenseRatio")
                        .HasPrecision(8, 6)
                        .HasColumnType("numeric(8,6)")
                        .HasColumnName("expense_ratio");

                    b.Property<string>("FundManager")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("fund_manager");

                    b.Property<DateOnly?>("InceptionDate")
                        .HasColumnType("date")
                        .HasColumnName("inception_date");

                    b.Property<DateTime>("LastUpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_updated_at_utc");

                    b.Property<string>("ReplicationType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("replication_type");

                    b.Property<string>("UnderlyingIndex")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("underlying_index");

                    b.HasKey("InstrumentId")
                        .HasName("pk_etf_ref_data");

                    b.ToTable("etf_ref_data", (string)null);
                });

            modelBuilder.Entity("InstrumentCatalogue.Core.Models.Instrument", b =>
                {
                    b.Property<Guid>("InstrumentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("instrument_id");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("character varying(25)")
                        .HasColumnName("country");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("character varying(25)")
                        .HasColumnName("currency");

                    b.Property<string>("Exchange")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("exchange");

                    b.Property<DateTime>("LastUpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_updated_at_utc");

                    b.Property<DateOnly?>("ListedDate")
                        .HasColumnType("date")
                        .HasColumnName("listed_date");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("type");

                    b.HasKey("InstrumentId")
                        .HasName("pk_instruments");

                    b.HasIndex("Type")
                        .HasDatabaseName("ix_instruments_type");

                    b.ToTable("instruments", (string)null);
                });

            modelBuilder.Entity("InstrumentCatalogue.Core.Models.InstrumentStatusHistory", b =>
                {
                    b.Property<Guid>("InstrumentStatusHistoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("instrument_status_history_id");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<DateOnly>("EffectiveDate")
                        .HasColumnType("date")
                        .HasColumnName("effective_date");

                    b.Property<Guid>("InstrumentId")
                        .HasColumnType("uuid")
                        .HasColumnName("instrument_id");

                    b.Property<string>("InstrumentStatus")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("instrument_status");

                    b.Property<DateTime>("LastUpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_updated_at_utc");

                    b.Property<string>("Notes")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("notes");

                    b.Property<DateOnly>("ValidFrom")
                        .HasColumnType("date")
                        .HasColumnName("valid_from");

                    b.Property<DateOnly>("ValidTo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("date")
                        .HasColumnName("valid_to")
                        .HasDefaultValueSql("'9999-12-31'::date");

                    b.HasKey("InstrumentStatusHistoryId")
                        .HasName("pk_instrument_status_history");

                    b.HasIndex("InstrumentId")
                        .HasDatabaseName("idx_status_current")
                        .HasFilter("valid_to = '9999-12-31'");

                    b.HasIndex("InstrumentId", "ValidFrom")
                        .IsUnique()
                        .HasDatabaseName("ix_instrument_status_history_instrument_id_valid_from");

                    b.ToTable("instrument_status_history", (string)null);
                });

            modelBuilder.Entity("InstrumentCatalogue.Core.Models.SymbolXRef", b =>
                {
                    b.Property<Guid>("SymbolXRefId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("symbol_x_ref_id");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<Guid>("InstrumentId")
                        .HasColumnType("uuid")
                        .HasColumnName("instrument_id");

                    b.Property<bool?>("IsPrimary")
                        .HasColumnType("boolean")
                        .HasColumnName("is_primary");

                    b.Property<DateTime>("LastUpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_updated_at_utc");

                    b.Property<string>("Symbol")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)")
                        .HasColumnName("symbol");

                    b.Property<int>("SymbologyId")
                        .HasColumnType("integer")
                        .HasColumnName("symbology_id");

                    b.Property<DateOnly>("ValidFrom")
                        .HasColumnType("date")
                        .HasColumnName("valid_from");

                    b.Property<DateOnly>("ValidTo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("date")
                        .HasColumnName("valid_to")
                        .HasDefaultValueSql("'9999-12-31'::date");

                    b.HasKey("SymbolXRefId")
                        .HasName("pk_symbol_x_ref");

                    b.HasIndex("Symbol")
                        .HasDatabaseName("idx_symbol_x_ref_current")
                        .HasFilter("valid_to = '9999-12-31'");

                    b.HasIndex("SymbologyId")
                        .HasDatabaseName("ix_symbol_x_ref_symbology_id");

                    b.HasIndex("InstrumentId", "SymbologyId", "ValidFrom")
                        .IsUnique()
                        .HasDatabaseName("ix_symbol_x_ref_instrument_id_symbology_id_valid_from");

                    b.ToTable("symbol_x_ref", (string)null);
                });

            modelBuilder.Entity("InstrumentCatalogue.Core.Models.Symbology", b =>
                {
                    b.Property<int>("SymbologyId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("symbology_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("SymbologyId"));

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)")
                        .HasColumnName("description");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<DateTime>("LastUpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_updated_at_utc");

                    b.Property<string>("TypeCode")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("type_code");

                    b.HasKey("SymbologyId")
                        .HasName("pk_symbologies");

                    b.HasIndex("TypeCode")
                        .IsUnique()
                        .HasDatabaseName("ix_symbologies_type_code");

                    b.ToTable("symbologies", (string)null);
                });

            modelBuilder.Entity("InstrumentCatalogue.Core.Models.Vendor", b =>
                {
                    b.Property<int>("VendorId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("vendor_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("VendorId"));

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<DateTime>("LastUpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_updated_at_utc");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.Property<string>("ShortCode")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("short_code");

                    b.HasKey("VendorId")
                        .HasName("pk_vendors");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("ix_vendors_name");

                    b.HasIndex("ShortCode")
                        .IsUnique()
                        .HasDatabaseName("ix_vendors_short_code");

                    b.ToTable("vendors", (string)null);
                });

            modelBuilder.Entity("InstrumentCatalogue.Core.Models.VendorInterface", b =>
                {
                    b.Property<int>("VendorInterfaceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("vendor_interface_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("VendorInterfaceId"));

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("Description")
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)")
                        .HasColumnName("description");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<DateTime>("LastUpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_updated_at_utc");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<string>("Protocol")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("protocol");

                    b.Property<int>("VendorId")
                        .HasColumnType("integer")
                        .HasColumnName("vendor_id");

                    b.HasKey("VendorInterfaceId")
                        .HasName("pk_vendor_interfaces");

                    b.HasIndex("VendorId", "Name")
                        .IsUnique()
                        .HasDatabaseName("ix_vendor_interfaces_vendor_id_name");

                    b.ToTable("vendor_interfaces", (string)null);
                });

            modelBuilder.Entity("InstrumentCatalogue.Core.Models.VendorInterfaceSymbolXRef", b =>
                {
                    b.Property<Guid>("VendorInterfaceSymbolXRefId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("vendor_interface_symbol_x_ref_id");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<DateTime>("LastUpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_updated_at_utc");

                    b.Property<DateTime>("ReceivedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("received_at_utc");

                    b.Property<Guid>("SymbolXRefId")
                        .HasColumnType("uuid")
                        .HasColumnName("symbol_x_ref_id");

                    b.Property<int>("VendorInterfaceId")
                        .HasColumnType("integer")
                        .HasColumnName("vendor_interface_id");

                    b.HasKey("VendorInterfaceSymbolXRefId")
                        .HasName("pk_vendor_interface_symbol_x_ref");

                    b.HasIndex("SymbolXRefId")
                        .HasDatabaseName("ix_vendor_interface_symbol_x_ref_symbol_x_ref_id");

                    b.HasIndex("VendorInterfaceId", "SymbolXRefId")
                        .IsUnique()
                        .HasDatabaseName("ix_vendor_interface_symbol_x_ref_vendor_interface_id_symbol_x_");

                    b.ToTable("vendor_interface_symbol_x_ref", (string)null);
                });

            modelBuilder.Entity("InstrumentCatalogue.Core.Models.BondRefData", b =>
                {
                    b.HasOne("InstrumentCatalogue.Core.Models.Instrument", null)
                        .WithOne("BondRefData")
                        .HasForeignKey("InstrumentCatalogue.Core.Models.BondRefData", "InstrumentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_bond_ref_data_instruments_instrument_id");
                });

            modelBuilder.Entity("InstrumentCatalogue.Core.Models.EquityRefData", b =>
                {
                    b.HasOne("InstrumentCatalogue.Core.Models.Instrument", null)
                        .WithOne("EquityRefData")
                        .HasForeignKey("InstrumentCatalogue.Core.Models.EquityRefData", "InstrumentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_equity_ref_data_instruments_instrument_id");
                });

            modelBuilder.Entity("InstrumentCatalogue.Core.Models.EtfRefData", b =>
                {
                    b.HasOne("InstrumentCatalogue.Core.Models.Instrument", null)
                        .WithOne("EtfRefData")
                        .HasForeignKey("InstrumentCatalogue.Core.Models.EtfRefData", "InstrumentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_etf_ref_data_instruments_instrument_id");
                });

            modelBuilder.Entity("InstrumentCatalogue.Core.Models.InstrumentStatusHistory", b =>
                {
                    b.HasOne("InstrumentCatalogue.Core.Models.Instrument", null)
                        .WithMany("StatusHistory")
                        .HasForeignKey("InstrumentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_instrument_status_history_instruments_instrument_id");
                });

            modelBuilder.Entity("InstrumentCatalogue.Core.Models.SymbolXRef", b =>
                {
                    b.HasOne("InstrumentCatalogue.Core.Models.Instrument", "Instrument")
                        .WithMany("Symbols")
                        .HasForeignKey("InstrumentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_symbol_x_ref_instruments_instrument_id");

                    b.HasOne("InstrumentCatalogue.Core.Models.Symbology", "Symbology")
                        .WithMany()
                        .HasForeignKey("SymbologyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_symbol_x_ref_symbologies_symbology_id");

                    b.Navigation("Instrument");

                    b.Navigation("Symbology");
                });

            modelBuilder.Entity("InstrumentCatalogue.Core.Models.VendorInterface", b =>
                {
                    b.HasOne("InstrumentCatalogue.Core.Models.Vendor", "Vendor")
                        .WithMany("Interfaces")
                        .HasForeignKey("VendorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_vendor_interfaces_vendors_vendor_id");

                    b.Navigation("Vendor");
                });

            modelBuilder.Entity("InstrumentCatalogue.Core.Models.VendorInterfaceSymbolXRef", b =>
                {
                    b.HasOne("InstrumentCatalogue.Core.Models.SymbolXRef", null)
                        .WithMany("VendorInterfaceSymbols")
                        .HasForeignKey("SymbolXRefId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_vendor_interface_symbol_x_ref_symbol_x_ref_symbol_x_ref_id");

                    b.HasOne("InstrumentCatalogue.Core.Models.VendorInterface", null)
                        .WithMany("SymbolXRefs")
                        .HasForeignKey("VendorInterfaceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_vendor_interface_symbol_x_ref_vendor_interfaces_vendor_inte");
                });

            modelBuilder.Entity("InstrumentCatalogue.Core.Models.Instrument", b =>
                {
                    b.Navigation("BondRefData");

                    b.Navigation("EquityRefData");

                    b.Navigation("EtfRefData");

                    b.Navigation("StatusHistory");

                    b.Navigation("Symbols");
                });

            modelBuilder.Entity("InstrumentCatalogue.Core.Models.SymbolXRef", b =>
                {
                    b.Navigation("VendorInterfaceSymbols");
                });

            modelBuilder.Entity("InstrumentCatalogue.Core.Models.Vendor", b =>
                {
                    b.Navigation("Interfaces");
                });

            modelBuilder.Entity("InstrumentCatalogue.Core.Models.VendorInterface", b =>
                {
                    b.Navigation("SymbolXRefs");
                });
#pragma warning restore 612, 618
        }
    }
}
